{
 "title": "Kafka Connect",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(kafka_connect_version_info, job)"
    }
   },
   {
    "name": "worker",
    "label": "Worker",
    "query": {
     "query": "label_values(kafka_connect_version_info{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "connector",
    "label": "Connector",
    "query": {
     "query": "label_values(kafka_connect_connector_status{job=\"$job\", instance=~\".*$worker.*\"}, connector)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total workers",
   "type": "stat",
   "description": "The number of active workers in Kafka Connect cluster.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_connect_worker_connector_count{job=\"$job\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Total connectors",
   "type": "stat",
   "description": "The total number of connectors.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_count{job=\"$job\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Total tasks",
   "type": "stat",
   "description": "The total number of connector tasks.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_total_task_count{job=\"$job\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Running tasks",
   "type": "stat",
   "description": "The total number of running connector tasks.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_running_task_count{job=\"$job\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Failed tasks",
   "type": "stat",
   "description": "The total number of failed connector tasks.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_failed_task_count{job=\"$job\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Paused tasks",
   "type": "stat",
   "description": "The total number of paused connector tasks.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_paused_task_count{job=\"$job\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Unassigned tasks",
   "type": "stat",
   "description": "The total number of unassigned connector tasks.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_unassigned_task_count{job=\"$job\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Destroyed tasks",
   "type": "stat",
   "description": "The total number of destroyed connector tasks.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_destroyed_task_count{job=\"$job\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Connector and task status",
   "type": "table",
   "description": "The current status of connectors and their tasks.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "min(kafka_connect_connector_status{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector, status)"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_total_task_count{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector)"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_running_task_count{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector) "
    },
    {
     "expr": "sum(kafka_connect_worker_connector_failed_task_count{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector)"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_paused_task_count{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector)"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_unassigned_task_count{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector)"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_destroyed_task_count{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector)"
    }
   ]
  },
  {
   "title": "Connector status over time",
   "type": "timeseries",
   "description": "The status of connectors over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(kafka_connect_connector_status{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\", status=\"running\"}) by (status)",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kafka_connect_connector_status{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\", status=\"failed\"}) by (status)",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(kafka_connect_connector_status{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\", status=\"paused\"}) by (status)",
     "legendFormat": "Paused"
    },
    {
     "expr": "sum(kafka_connect_connector_status{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\", status=\"unassigned\"}) by (status)",
     "legendFormat": "Unassigned"
    },
    {
     "expr": "sum(kafka_connect_connector_status{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\", status=\"destroyed\"}) by (status)",
     "legendFormat": "Destroyed"
    }
   ]
  },
  {
   "title": "Connector task status over time",
   "type": "timeseries",
   "description": "The status of connector tasks over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_running_task_count{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) > 0",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_failed_task_count{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) > 0",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_paused_task_count{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) > 0",
     "legendFormat": "Paused"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_unassigned_task_count{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) > 0",
     "legendFormat": "Unassigned"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_destroyed_task_count{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) > 0",
     "legendFormat": "Destroyed"
    }
   ]
  },
  {
   "title": "Time since last rebalance [$worker]",
   "type": "stat",
   "description": "The time since last rebalance of Kafka Connect worker.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 21 },
   "repeat": "worker",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_worker_rebalance_time_since_last_rebalance_ms{job=\"$job\", instance=~\".*$worker.*\"} >= 0"
    }
   ]
  },
  {
   "title": "Debezium Oracle Connector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "SCNs",
     "type": "table",
     "description": "Information about Oracle system change numbers.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "max(debezium_connector_currentscn{job=\"$job\", instance=~\".*$worker.*\", plugin=\"oracle\", context=\"streaming\", connector=~\"$connector\"}) by (connector) > 0"
      },
      {
       "expr": "max(debezium_connector_oldestscn{job=\"$job\", instance=~\".*$worker.*\", plugin=\"oracle\", context=\"streaming\", connector=~\"$connector\"}) by (connector) > 0"
      },
      {
       "expr": "max(debezium_connector_committedscn{job=\"$job\", instance=~\".*$worker.*\", plugin=\"oracle\", context=\"streaming\", connector=~\"$connector\"}) by (connector) > 0"
      },
      {
       "expr": "max(debezium_connector_offsetscn{job=\"$job\", instance=~\".*$worker.*\", plugin=\"oracle\", context=\"streaming\", connector=~\"$connector\"}) by (connector) > 0"
      },
      {
       "expr": "max(debezium_connector_scnfreezecount{job=\"$job\", instance=~\".*$worker.*\", plugin=\"oracle\", context=\"streaming\", connector=~\"$connector\"}) by (connector) > 0"
      }
     ]
    },
    {
     "title": "Transaction buffers",
     "type": "table",
     "description": "Statistics of connector transaction buffers.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "max(debezium_connector_numberofactivetransactions{job=\"$job\", instance=~\".*$worker.*\", plugin=\"oracle\", context=\"streaming\", connector=~\"$connector\"}) by (connector)"
      },
      {
       "expr": "max(debezium_connector_numberofcommittedtransactions{job=\"$job\", instance=~\".*$worker.*\", plugin=\"oracle\", context=\"streaming\", connector=~\"$connector\"}) by (connector)"
      },
      {
       "expr": "max(debezium_connector_numberofoversizedtransactions{job=\"$job\", instance=~\".*$worker.*\", plugin=\"oracle\", context=\"streaming\", connector=~\"$connector\"}) by (connector)"
      },
      {
       "expr": "max(debezium_connector_numberofrolledbacktransactions{job=\"$job\", instance=~\".*$worker.*\", plugin=\"oracle\", context=\"streaming\", connector=~\"$connector\"}) by (connector)"
      },
      {
       "expr": "max(debezium_connector_committhroughput{job=\"$job\", instance=~\".*$worker.*\", plugin=\"oracle\", context=\"streaming\", connector=~\"$connector\"}) by (connector)"
      }
     ]
    },
    {
     "title": "Lag from database in transaction buffer",
     "type": "timeseries",
     "description": "The time difference in milliseconds between when a change occurred in the transaction logs and when its added to the transaction buffer.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(debezium_connector_lagfromsourceinmilliseconds{job=\"$job\", instance=~\".*$worker.*\", plugin=\"oracle\", context=\"streaming\", connector=~\"$connector\"}) by (connector)",
       "legendFormat": "{{connector}}"
      }
     ]
    },
    {
     "title": "Mining batch time",
     "type": "timeseries",
     "description": "The duration for processing the last LogMiner query batch results in milliseconds.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(debezium_connector_millisecondtosleepbetweenminingquery{job=\"$job\", instance=~\".*$worker.*\", plugin=\"oracle\", context=\"streaming\", connector=~\"$connector\"}) by (connector)",
       "legendFormat": "sleep between mining query [connector={{connector}}]"
      },
      {
       "expr": "max(debezium_connector_lastminingsessionstarttimeinmilliseconds{job=\"$job\", instance=~\".*$worker.*\", plugin=\"oracle\", context=\"streaming\", connector=~\"$connector\"}) by (connector)",
       "legendFormat": "start mining session [connector={{connector}}]"
      },
      {
       "expr": "max(debezium_connector_lastdurationoffetchqueryinmilliseconds{job=\"$job\", instance=~\".*$worker.*\", plugin=\"oracle\", context=\"streaming\", connector=~\"$connector\"}) by (connector)",
       "legendFormat": "fetch query [connector={{connector}}]"
      },
      {
       "expr": "idelta(debezium_connector_totalresultsetnexttimeinmilliseconds{job=\"$job\", instance=~\".*$worker.*\", plugin=\"oracle\", context=\"streaming\", connector=~\"$connector\"}[5m]) >= 0",
       "legendFormat": "result set next [connector={{connector}}]"
      },
      {
       "expr": "max(debezium_connector_lastbatchprocessingtimeinmilliseconds{job=\"$job\", instance=~\".*$worker.*\", plugin=\"oracle\", context=\"streaming\", connector=~\"$connector\"}) by (connector)",
       "legendFormat": "batch processing [connector={{connector}}]"
      }
     ]
    },
    {
     "title": "Processed rows per second",
     "type": "timeseries",
     "description": "The number of rows processed per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(debezium_connector_totalprocessedrows{job=\"$job\", instance=~\".*$worker.*\", plugin=\"oracle\", context=\"streaming\", connector=~\"$connector\"}[5m])",
       "legendFormat": "{{connector}}"
      }
     ]
    },
    {
     "title": "Mining batch size",
     "type": "timeseries",
     "description": "The number of entries fetched by the log mining query per database round-trip.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "max(debezium_connector_batchsize{job=\"$job\", instance=~\".*$worker.*\", plugin=\"oracle\", context=\"streaming\", connector=~\"$connector\"}) by (connector)",
       "legendFormat": "{{connector}}"
      }
     ]
    },
    {
     "title": "Mining session consumption",
     "type": "timeseries",
     "description": "The current mining session’s user/process global area (UGA/PGA) memory consumption in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(debezium_connector_miningsessionuserglobalareamemoryinbytes{job=\"$job\", instance=~\".*$worker.*\", plugin=\"oracle\", context=\"streaming\", connector=~\"$connector\"}) by (connector)",
       "legendFormat": "UGA: {{connector}}"
      },
      {
       "expr": "max(debezium_connector_miningsessionprocessglobalareamemoryinbytes{job=\"$job\", instance=~\".*$worker.*\", plugin=\"oracle\", context=\"streaming\", connector=~\"$connector\"}) by (connector)",
       "legendFormat": "PGA: {{connector}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Debezium Connector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connectors",
     "type": "table",
     "description": "Statistics of Debezium connectors.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "min(debezium_connector_connected{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector)"
      },
      {
       "expr": "max(debezium_connector_millisecondssincelastevent{job=\"$job\", instance=~\".*$worker.*\", context=\"snapshot\", connector=~\"$connector\"} >= 0) by (connector)"
      },
      {
       "expr": "max(debezium_connector_millisecondssincelastevent{job=\"$job\", instance=~\".*$worker.*\", context=\"streaming\", connector=~\"$connector\"} >= 0) by (connector)"
      },
      {
       "expr": "sum(debezium_connector_totalnumberofeventsseen{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector)"
      },
      {
       "expr": "sum(debezium_connector_totalnumberofcreateeventsseen{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector)"
      },
      {
       "expr": "sum(debezium_connector_totalnumberofupdateeventsseen{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector)"
      },
      {
       "expr": "sum(debezium_connector_totalnumberofdeleteeventsseen{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector)"
      },
      {
       "expr": "sum(debezium_connector_numberofeventsfiltered{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector)"
      }
     ]
    },
    {
     "title": "Snapshot status",
     "type": "table",
     "description": "The status of Debezium connector snapshots.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "min(debezium_connector_totaltablecount{job=\"$job\", instance=~\".*$worker.*\", context=\"snapshot\", connector=~\"$connector\"}) by (connector)"
      },
      {
       "expr": "min(debezium_connector_remainingtablecount{job=\"$job\", instance=~\".*$worker.*\", context=\"snapshot\", connector=~\"$connector\"}) by (connector)"
      },
      {
       "expr": "min(debezium_connector_snapshotrunning{job=\"$job\", instance=~\".*$worker.*\", context=\"snapshot\", connector=~\"$connector\"}) by (connector)"
      },
      {
       "expr": "max(debezium_connector_snapshotpaused{job=\"$job\", instance=~\".*$worker.*\", context=\"snapshot\", connector=~\"$connector\"}) by (connector)"
      },
      {
       "expr": "max(debezium_connector_snapshotaborted{job=\"$job\", instance=~\".*$worker.*\", context=\"snapshot\", connector=~\"$connector\"}) by (connector)"
      },
      {
       "expr": "min(debezium_connector_snapshotcompleted{job=\"$job\", instance=~\".*$worker.*\", context=\"snapshot\", connector=~\"$connector\"}) by (connector)"
      },
      {
       "expr": "max(debezium_connector_snapshotdurationinseconds{job=\"$job\", instance=~\".*$worker.*\", context=\"snapshot\", connector=~\"$connector\"}) by (connector)"
      },
      {
       "expr": "max(debezium_connector_snapshotpauseddurationinseconds{job=\"$job\", instance=~\".*$worker.*\", context=\"snapshot\", connector=~\"$connector\"}) by (connector)"
      }
     ]
    },
    {
     "title": "Source record poll queue size",
     "type": "timeseries",
     "description": "The current size of the poll queue.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(debezium_connector_queuetotalcapacity{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector)",
       "legendFormat": "Limit: {{connector}}"
      },
      {
       "expr": "max(debezium_connector_queuetotalcapacity{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}-debezium_connector_queueremainingcapacity{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector, task)",
       "legendFormat": "Used: {{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Source record poll queue size in bytes",
     "type": "timeseries",
     "description": "The current size of the poll queue in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(debezium_connector_maxqueuesizeinbytes{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector)",
       "legendFormat": "Limit: {{connector}}"
      },
      {
       "expr": "max(debezium_connector_currentqueuesizeinbytes{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector, task)",
       "legendFormat": "Used: {{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Time behind source event",
     "type": "timeseries",
     "description": "The number of milliseconds between the last change event’s timestamp and the connector processing it. The values will incoporate any differences between the clocks on the machines where the database server and the connector are running.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(debezium_connector_millisecondsbehindsource{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector, task) > 0",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Source records polled per second (before transformation)",
     "type": "timeseries",
     "description": "The per-second number of source records produced/polled (before transformation) by connector task.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(kafka_connect_source_task_source_record_poll_total{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}[5m])",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Sink records read per second (before transformation)",
     "type": "timeseries",
     "description": "The per-second number of sink records read from Kafka for connector task. This is before transformations are applied.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(kafka_connect_sink_task_sink_record_read_total{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}[5m])",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Source records written per second (after transformation)",
     "type": "timeseries",
     "description": "The per-second number of source records output from the transformations and written to Kafka for connector task. This is after transformations are applied and excludes any records filtered out by the transformations.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(kafka_connect_source_task_source_record_write_total{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}[5m])",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Sink records sent per second (after transformation)",
     "type": "timeseries",
     "description": "The per-second number of sink records output from the transformations and sent/put to connector task. This is after transformations are applied and excludes any records filtered out by the transformations.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(kafka_connect_sink_task_sink_record_send_total{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}[5m])",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Source record poll time",
     "type": "timeseries",
     "description": "The average time in milliseconds taken by connector task to poll for a batch of source records.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(kafka_connect_source_task_poll_batch_avg_time_ms{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector, task)",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Sink record put time",
     "type": "timeseries",
     "description": "The average time in milliseconds taken by connector task to put a batch of sinks records.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(kafka_connect_sink_task_put_batch_avg_time_ms{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector, task)",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Task batch size",
     "type": "timeseries",
     "description": "The average size of the batches processed by the connector task.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "kafka_connect_connector_task_batch_size_avg{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Topic partition assignment",
     "type": "timeseries",
     "description": "The number of topic partitions assigned to connector task.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "max(kafka_connect_sink_task_partition_count{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\", task=~\".+\"}) by (connector, task)",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Producer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Producers",
     "type": "table",
     "description": "Statistics of connector producers for topics.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "min(label_join(kafka_producer_topic_record_send_total{job=\"$job\", instance=~\".*$worker.*\", clientId=~\"connector-producer-$connector.*\", topic=~\".+\"}, \"clientIdAndTopic\", \"-\", \"clientId\", \"topic\")) by (clientIdAndTopic, clientId, topic)"
      },
      {
       "expr": "min(label_join(kafka_producer_topic_byte_total{job=\"$job\", instance=~\".*$worker.*\", clientId=~\"connector-producer-$connector.*\", topic=~\".+\"}, \"clientIdAndTopic\", \"-\", \"clientId\", \"topic\")) by (clientIdAndTopic, clientId, topic)"
      }
     ]
    },
    {
     "title": "Records sent per second",
     "type": "timeseries",
     "description": "The number of records sent per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(kafka_producer_topic_record_send_total{job=\"$job\", instance=~\".*$worker.*\", clientId=~\"connector-producer-$connector.*\", topic=~\".+\"}[5m])",
       "legendFormat": "{{clientId}} [topic={{topic}}]"
      }
     ]
    },
    {
     "title": "Records in bytes sent per second",
     "type": "timeseries",
     "description": "The number of records in bytes sent per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(kafka_producer_topic_byte_total{job=\"$job\", instance=~\".*$worker.*\", clientId=~\"connector-producer-$connector.*\"}[5m])",
       "legendFormat": "{{clientId}} [topic={{topic}}]"
      }
     ]
    },
    {
     "title": "Producer record queue time",
     "type": "timeseries",
     "description": "The average time in milliseconds record batches spent in the send buffer.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(kafka_producer_record_queue_time_avg{job=\"$job\", instance=~\".*$worker.*\", clientId=~\"connector-producer-$connector.*\"}) by (clientId)",
       "legendFormat": "{{clientId}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consumers",
     "type": "table",
     "description": "Statistics of connector consumers for topics.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "min(label_join(kafka_consumer_fetch_manager_records_consumed_total{job=\"$job\", instance=~\".*$worker.*\", clientId=~\"connector-consumer-$connector.*\", topic=~\".+\"}, \"clientIdAndTopic\", \"-\", \"clientId\", \"topic\")) by (clientIdAndTopic, clientId, topic)"
      },
      {
       "expr": "min(label_join(kafka_consumer_fetch_manager_bytes_consumed_total{job=\"$job\", instance=~\".*$worker.*\", clientId=~\"connector-consumer-$connector.*\", topic=~\".+\"}, \"clientIdAndTopic\", \"-\", \"clientId\", \"topic\")) by (clientIdAndTopic, clientId, topic)"
      }
     ]
    },
    {
     "title": "Records consumed per second",
     "type": "timeseries",
     "description": "The number of records consumed per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(kafka_consumer_fetch_manager_records_consumed_total{job=\"$job\", instance=~\".*$worker.*\", clientId=~\"connector-consumer-$connector.*\", topic=~\".+\"}[5m])",
       "legendFormat": "{{clientId}} [topic={{topic}}]"
      }
     ]
    },
    {
     "title": "Records in bytes consumed per second",
     "type": "timeseries",
     "description": "The number of records in bytes consumed per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(kafka_consumer_fetch_manager_bytes_consumed_total{job=\"$job\", instance=~\".*$worker.*\", clientId=~\"connector-consumer-$connector.*\", topic=~\".+\"}[5m])",
       "legendFormat": "{{clientId}} [topic={{topic}}]"
      }
     ]
    },
    {
     "title": "Consumer lag",
     "type": "timeseries",
     "description": "The lag in terms of number of records by clients. An increasing value over time is your best indication that the consumer group is not keeping up with the producers.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "sum(kafka_consumer_fetch_manager_records_lag{job=\"$job\", instance=~\".*$worker.*\", clientId=~\"connector-consumer-$connector.*\", topic=~\".+\"}) by (clientId, topic)",
       "legendFormat": "{{clientId}} [topic={{topic}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Timing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Source record processing latency",
     "type": "timeseries",
     "description": "The average processing latency of a source record in milliseconds, measured by comparing the source timestamp with the system time when it has been processed by the task.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(data_transfer_source_task_record_process_avg_latency_ms{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector, task, sourceType, sourceName)",
       "legendFormat": "{{connector}}-{{task}} [{{sourceType}}={{sourceName}}]"
      }
     ]
    },
    {
     "title": "Source record poll queue time",
     "type": "timeseries",
     "description": "The average time of a source record in milliseconds when it waits in the poll queue.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(data_transfer_source_task_record_poll_queue_avg_time_ms{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector, task, sourceType, sourceName)",
       "legendFormat": "{{connector}}-{{task}} [{{sourceType}}={{sourceName}}]"
      }
     ]
    },
    {
     "title": "Source record end-to-end time",
     "type": "timeseries",
     "description": "The average end-to-end time of a source record in milliseconds, measured by comparing the source timestamp with the system time when the record sent to Kafka broker has been acknowledged.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(data_transfer_source_task_record_end_to_end_avg_time_ms{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector, task, sourceType, sourceName)",
       "legendFormat": "{{connector}}-{{task}} [{{sourceType}}={{sourceName}}]"
      }
     ]
    },
    {
     "title": "Source record total delivery time",
     "type": "timeseries",
     "description": "The average total delivery time of a source record in milliseconds, measured by comparing the processing timestamp with the system time when the record sent to Kafka broker has been acknowledged.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(data_transfer_source_task_record_total_delivery_avg_time_ms{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector, task, sourceType, sourceName)",
       "legendFormat": "{{connector}}-{{task}} [{{sourceType}}={{sourceName}}]"
      }
     ]
    },
    {
     "title": "Sink record end-to-end time",
     "type": "timeseries",
     "description": "The average end-to-end time of a sink record in milliseconds, measured by comparing the source timestamp with the system time when the record was written to the downstream system.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(data_transfer_sink_task_record_end_to_end_avg_time_ms{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector, task, sourceType, sourceName)",
       "legendFormat": "{{connector}}-{{task}} [{{sourceType}}={{sourceName}}]"
      }
     ]
    },
    {
     "title": "Sink record total delivery time",
     "type": "timeseries",
     "description": "The average total delivery time of a sink record in milliseconds, measured by comparing the processing timestamp with the system time when the record was written to the downstream system.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(data_transfer_sink_task_record_total_delivery_avg_time_ms{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector, task, sourceType, sourceName)",
       "legendFormat": "{{connector}}-{{task}} [{{sourceType}}={{sourceName}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Worker: $worker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "repeat": "worker",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage [$worker]",
     "type": "timeseries",
     "description": "The information about CPU usage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"$job\", instance=~\".*$worker.*\"}[5m])",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Threads [$worker]",
     "type": "timeseries",
     "description": "The information about JVM threads.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "jvm_threads_current{job=\"$job\", instance=~\".*$worker.*\"}",
       "legendFormat": "Total threads"
      },
      {
       "expr": "jvm_threads_daemon{job=\"$job\", instance=~\".*$worker.*\"}",
       "legendFormat": "Daemon threads"
      },
      {
       "expr": "jvm_threads_deadlocked{job=\"$job\", instance=~\".*$worker.*\"}",
       "legendFormat": "Deadlocked threads"
      }
     ]
    },
    {
     "title": "Heap memory usage [$worker]",
     "type": "timeseries",
     "description": "The information about JVM heap memory usage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{area=\"heap\", job=\"$job\", instance=~\".*$worker.*\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_bytes_max{area=\"heap\", job=\"$job\", instance=~\".*$worker.*\"}",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Garbage collections triggered per second [$worker]",
     "type": "timeseries",
     "description": "The number of garbage collections triggered per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_count{job=\"$job\", instance=~\".*$worker.*\"}[5m])",
       "legendFormat": "{{gc}}"
      }
     ]
    },
    {
     "title": "Heap memory usage in percent [$worker]",
     "type": "timeseries",
     "description": "The information about JVM heap memory usage in percent (%).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * jvm_memory_bytes_used{area=\"heap\", job=\"$job\", instance=~\".*$worker.*\"} / jvm_memory_bytes_max{area=\"heap\", job=\"$job\", instance=~\".*$worker.*\"}",
       "legendFormat": "Used"
      },
      { "expr": "100", "legendFormat": "Limit" }
     ]
    },
    {
     "title": "Time spent in garbage collection [$worker]",
     "type": "timeseries",
     "description": "The time in seconds spent in garbage collection.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{job=\"$job\", instance=~\".*$worker.*\"}[5m])",
       "legendFormat": "{{gc}}"
      }
     ]
    }
   ]
  }
 ]
}