{
 "title": "Kafka Streams",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(kafka_streams_version_info, job)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(kafka_streams_version_info{job=~\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Application status",
   "type": "stat",
   "description": "The status of Kafka Streams application.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_streams_failed_stream_threads{job=\"$job\"}) + (sum(kafka_streams_state{job=\"$job\", instance=~\".*$server.*\", state=\"ERROR\"}) or vector(0))"
    }
   ]
  },
  {
   "title": "Application ID",
   "type": "stat",
   "description": "The ID of Kafka Streams application.",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by (application_id) (kafka_streams_application_id_info{job=\"$job\"})",
     "legendFormat": "{{application_id}}"
    }
   ]
  },
  {
   "title": "Kafka version",
   "type": "stat",
   "description": "The version of Kafka Streams library.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by (version) (kafka_streams_version_info{job=\"$job\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Total stream instances",
   "type": "stat",
   "description": "The total number of stream instances.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_streams_state{job=\"$job\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Total stream threads",
   "type": "stat",
   "description": "The total number of stream threads.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kafka_streams_alive_stream_threads{job=\"$job\"}) - sum(kafka_streams_failed_stream_threads{job=\"$job\"})) or vector(0)"
    }
   ]
  },
  {
   "title": "Failed stream threads",
   "type": "stat",
   "description": "The total number of failed stream threads.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_streams_failed_stream_threads{job=\"$job\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Running thread tasks",
   "type": "stat",
   "description": "The total number of running thread tasks.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kafka_streams_thread_task_created_total{job=\"$job\"}) - sum(kafka_streams_thread_task_closed_total{job=\"$job\"})) or vector(0)"
    }
   ]
  },
  {
   "title": "Stream instance state over time",
   "type": "timeseries",
   "description": "The state of stream instances over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(kafka_streams_state{job=\"$job\", instance=~\".*$server.*\", state=\"CREATED\"}) by (state)",
     "legendFormat": "Created"
    },
    {
     "expr": "sum(kafka_streams_state{job=\"$job\", instance=~\".*$server.*\", state=\"RUNNING\"}) by (state)",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kafka_streams_state{job=\"$job\", instance=~\".*$server.*\", state=\"REBALANCING\"}) by (state)",
     "legendFormat": "Rebalancing"
    },
    {
     "expr": "sum(kafka_streams_state{job=\"$job\", instance=~\".*$server.*\", state=\"ERROR\"}) by (state)",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(kafka_streams_state{job=\"$job\", instance=~\".*$server.*\", state=\"PENDING SHUTDOWN\"}) by (state)",
     "legendFormat": "Pending shutdown"
    },
    {
     "expr": "sum(kafka_streams_state{job=\"$job\", instance=~\".*$server.*\", state=\"NOT RUNNING\"}) by (state)",
     "legendFormat": "Not running"
    }
   ]
  },
  {
   "title": "Stream thread status over time",
   "type": "timeseries",
   "description": "The status of stream threads over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum(kafka_streams_alive_stream_threads{job=\"$job\", instance=~\".*$server.*\"}) > 0",
     "legendFormat": "Alive"
    }
   ]
  },
  {
   "title": "Stream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Stream thread operations per second",
     "type": "timeseries",
     "description": "The per-second number of operations performed by the stream thread.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(kafka_streams_thread_commit_total{job=\"$job\", instance=~\".*$server.*\"}[5m]) > 0",
       "legendFormat": "Commit [thread={{threadId}}]"
      },
      {
       "expr": "rate(kafka_streams_thread_poll_total{job=\"$job\", instance=~\".*$server.*\"}[5m]) > 0",
       "legendFormat": "Poll [thread={{threadId}}]"
      },
      {
       "expr": "rate(kafka_streams_thread_process_total{job=\"$job\", instance=~\".*$server.*\"}[5m]) > 0",
       "legendFormat": "Process [thread={{threadId}}]"
      },
      {
       "expr": "rate(kafka_streams_thread_punctuate_total{job=\"$job\", instance=~\".*$server.*\"}[5m]) > 0",
       "legendFormat": "Punctuate [thread={{threadId}}]"
      }
     ]
    },
    {
     "title": "Stream thread latency",
     "type": "timeseries",
     "description": "The average time in nanoseconds taken by the stream thread to perform an operation.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "kafka_streams_thread_commit_latency_avg{job=\"$job\", instance=~\".*$server.*\"} > 0",
       "legendFormat": "Commit [thread={{threadId}}]"
      },
      {
       "expr": "kafka_streams_thread_poll_latency_avg{job=\"$job\", instance=~\".*$server.*\"} > 0",
       "legendFormat": "Poll [thread={{threadId}}]"
      },
      {
       "expr": "kafka_streams_thread_process_latency_avg{job=\"$job\", instance=~\".*$server.*\"} > 0",
       "legendFormat": "Process [thread={{threadId}}]"
      },
      {
       "expr": "kafka_streams_thread_punctuate_latency_avg{job=\"$job\", instance=~\".*$server.*\"} > 0",
       "legendFormat": "Punctuate [thread={{threadId}}]"
      }
     ]
    },
    {
     "title": "Records polled/processed per iteration",
     "type": "timeseries",
     "description": "The average number of records polled/processed in one iteration.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "kafka_streams_thread_poll_records_avg{job=\"$job\", instance=~\".*$server.*\"} > 0",
       "legendFormat": "Poll [thread={{threadId}}]"
      },
      {
       "expr": "kafka_streams_thread_process_records_avg{job=\"$job\", instance=~\".*$server.*\"} > 0",
       "legendFormat": "Process [thread={{threadId}}]"
      }
     ]
    },
    {
     "title": "State store space size",
     "type": "timeseries",
     "description": "The approximate space size in bytes used by the state store.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (storeId) ({__name__=~\"kafka_streams_state_size_all_mem_tables|kafka_streams_state_block_cache_usage|kafka_streams_state_estimate_table_readers_mem\", job=\"$job\", instance=~\".*$server.*\", storeId!=\"\"})",
       "legendFormat": "Off-heap [store={{storeId}}]"
      },
      {
       "expr": "sum(kafka_streams_state_total_sst_files_size{job=\"$job\", instance=~\".*$server.*\", storeId!=\"\"}) by (storeId)",
       "legendFormat": "SST-files [store={{storeId}}]"
      }
     ]
    },
    {
     "title": "State store operations per second",
     "type": "timeseries",
     "description": "The per-second number of operations performed by the state store.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(kafka_streams_state_get_rate{job=\"$job\", instance=~\".*$server.*\", storeId!=\"\"}) by (storeId) > 0",
       "legendFormat": "Get [store={{storeId}}]"
      },
      {
       "expr": "sum(kafka_streams_state_put_rate{job=\"$job\", instance=~\".*$server.*\", storeId!=\"\"}) by (storeId) > 0",
       "legendFormat": "Put [store={{storeId}}]"
      },
      {
       "expr": "sum(kafka_streams_state_delete_rate{job=\"$job\", instance=~\".*$server.*\", storeId!=\"\"}) by (storeId) > 0",
       "legendFormat": "Delete [store={{storeId}}]"
      },
      {
       "expr": "sum(kafka_streams_state_flush_rate{job=\"$job\", instance=~\".*$server.*\", storeId!=\"\"}) by (storeId) > 0",
       "legendFormat": "Flush [store={{storeId}}]"
      },
      {
       "expr": "sum(kafka_streams_state_restore_rate{job=\"$job\", instance=~\".*$server.*\", storeId!=\"\"}) by (storeId) > 0",
       "legendFormat": "Restore [store={{storeId}}]"
      }
     ]
    },
    {
     "title": "State store latency",
     "type": "timeseries",
     "description": "The average time in nanoseconds taken by the state store to perform an operation.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "sum(kafka_streams_state_get_latency_avg{job=\"$job\", instance=~\".*$server.*\", storeId!=\"\"}) by (storeId) > 0",
       "legendFormat": "Get [store={{storeId}}]"
      },
      {
       "expr": "sum(kafka_streams_state_put_latency_avg{job=\"$job\", instance=~\".*$server.*\", storeId!=\"\"}) by (storeId) > 0",
       "legendFormat": "Put [store={{storeId}}]"
      },
      {
       "expr": "sum(kafka_streams_state_delete_latency_avg{job=\"$job\", instance=~\".*$server.*\", storeId!=\"\"}) by (storeId) > 0",
       "legendFormat": "Delete [store={{storeId}}]"
      },
      {
       "expr": "sum(kafka_streams_flush_delete_latency_avg{job=\"$job\", instance=~\".*$server.*\", storeId!=\"\"}) by (storeId) > 0",
       "legendFormat": "Flush [store={{storeId}}]"
      },
      {
       "expr": "sum(kafka_streams_restore_delete_latency_avg{job=\"$job\", instance=~\".*$server.*\", storeId!=\"\"}) by (storeId) > 0",
       "legendFormat": "Restore [store={{storeId}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consumers",
     "type": "table",
     "description": "Statistics of stream consumers for topics.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "min(label_join(kafka_consumer_fetch_manager_records_consumed_total{job=\"$job\", instance=~\".*$server.*\", clientId=~\".+\", topic=~\".+\"}, \"clientIdAndTopic\", \"-\", \"clientId\", \"topic\")) by (clientIdAndTopic, clientId, topic)"
      },
      {
       "expr": "min(label_join(kafka_consumer_fetch_manager_bytes_consumed_total{job=\"$job\", instance=~\".*$server.*\", clientId=~\".+\", topic=~\".+\"}, \"clientIdAndTopic\", \"-\", \"clientId\", \"topic\")) by (clientIdAndTopic, clientId, topic)"
      }
     ]
    },
    {
     "title": "Records consumed per second",
     "type": "timeseries",
     "description": "The number of records consumed per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(kafka_consumer_fetch_manager_records_consumed_total{job=\"$job\", instance=~\".*$server.*\", clientId=~\".+\", topic=~\".+\"}[5m])",
       "legendFormat": "{{clientId}} [topic={{topic}}]"
      }
     ]
    },
    {
     "title": "Records in bytes consumed per second",
     "type": "timeseries",
     "description": "The number of records in bytes consumed per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(kafka_consumer_fetch_manager_bytes_consumed_total{job=\"$job\", instance=~\".*$server.*\", clientId=~\".+\", topic=~\".+\"}[5m])",
       "legendFormat": "{{clientId}} [topic={{topic}}]"
      }
     ]
    },
    {
     "title": "Consumer lag",
     "type": "timeseries",
     "description": "The lag in terms of number of records by clients. An increasing value over time is your best indication that the consumer group is not keeping up with the producers.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum(kafka_consumer_fetch_manager_records_lag{job=\"$job\", instance=~\".*$server.*\", clientId=~\".+\", topic=~\".+\"}) by (clientId, topic)",
       "legendFormat": "{{clientId}} [topic={{topic}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Producer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Producers",
     "type": "table",
     "description": "Statistics of stream producers for topics.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "min(label_join(kafka_producer_topic_record_send_total{job=\"$job\", instance=~\".*$server.*\", clientId=~\".+\", topic=~\".+\"}, \"clientIdAndTopic\", \"-\", \"clientId\", \"topic\")) by (clientIdAndTopic, clientId, topic)"
      },
      {
       "expr": "min(label_join(kafka_producer_topic_byte_total{job=\"$job\", instance=~\".*$server.*\", clientId=~\".+\", topic=~\".+\"}, \"clientIdAndTopic\", \"-\", \"clientId\", \"topic\")) by (clientIdAndTopic, clientId, topic)"
      }
     ]
    },
    {
     "title": "Records sent per second",
     "type": "timeseries",
     "description": "The number of records sent per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(kafka_producer_topic_record_send_total{job=\"$job\", instance=~\".*$server.*\", clientId=~\".+\", topic=~\".+\"}[5m])",
       "legendFormat": "{{clientId}} [topic={{topic}}]"
      }
     ]
    },
    {
     "title": "Records in bytes sent per second",
     "type": "timeseries",
     "description": "The number of records in bytes sent per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(kafka_producer_topic_byte_total{job=\"$job\", instance=~\".*$server.*\", clientId=~\".+\"}[5m])",
       "legendFormat": "{{clientId}} [topic={{topic}}]"
      }
     ]
    },
    {
     "title": "Producer record queue time",
     "type": "timeseries",
     "description": "The average time in milliseconds record batches spent in the send buffer.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(kafka_producer_record_queue_time_avg{job=\"$job\", instance=~\".*$server.*\", clientId=~\".+\"}) by (clientId)",
       "legendFormat": "{{clientId}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Server: $server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "repeat": "server",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage [$server]",
     "type": "timeseries",
     "description": "The information about CPU usage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"$job\", instance=~\".*$server.*\"}[5m])",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Threads [$server]",
     "type": "timeseries",
     "description": "The information about JVM threads.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "jvm_threads_current{job=\"$job\", instance=~\".*$server.*\"}",
       "legendFormat": "Total threads"
      },
      {
       "expr": "jvm_threads_daemon{job=\"$job\", instance=~\".*$server.*\"}",
       "legendFormat": "Daemon threads"
      },
      {
       "expr": "jvm_threads_deadlocked{job=\"$job\", instance=~\".*$server.*\"}",
       "legendFormat": "Deadlocked threads"
      }
     ]
    },
    {
     "title": "Heap memory usage [$server]",
     "type": "timeseries",
     "description": "The information about JVM heap memory usage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{area=\"heap\", job=\"$job\", instance=~\".*$server.*\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_bytes_max{area=\"heap\", job=\"$job\", instance=~\".*$server.*\"}",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Garbage collections triggered per second [$server]",
     "type": "timeseries",
     "description": "The number of garbage collections triggered per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_count{job=\"$job\", instance=~\".*$server.*\"}[5m])",
       "legendFormat": "{{gc}}"
      }
     ]
    },
    {
     "title": "Heap memory usage in percent [$server]",
     "type": "timeseries",
     "description": "The information about JVM heap memory usage in percent (%).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * jvm_memory_bytes_used{area=\"heap\", job=\"$job\", instance=~\".*$server.*\"} / jvm_memory_bytes_max{area=\"heap\", job=\"$job\", instance=~\".*$server.*\"}",
       "legendFormat": "Used"
      },
      { "expr": "100", "legendFormat": "Limit" }
     ]
    },
    {
     "title": "Time spent in garbage collection [$server]",
     "type": "timeseries",
     "description": "The time in seconds spent in garbage collection.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{job=\"$job\", instance=~\".*$server.*\"}[5m])",
       "legendFormat": "{{gc}}"
      }
     ]
    }
   ]
  }
 ]
}