{
 "title": "Kafka Mirror Maker",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(kafka_connect_worker_connector_count, job)"
    }
   },
   {
    "name": "worker",
    "label": "Worker",
    "query": {
     "query": "label_values(kafka_connect_worker_connector_count{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "connector",
    "label": "Connector",
    "query": {
     "query": "label_values(kafka_connect_connector_status{job=\"$job\", instance=~\".*$worker.*\"}, connector)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total workers",
   "type": "stat",
   "description": "The number of active workers in Kafka Mirror Maker cluster.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_connect_worker_connector_count{job=\"$job\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Total connectors",
   "type": "stat",
   "description": "The total number of connectors.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_count{job=\"$job\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Total tasks",
   "type": "stat",
   "description": "The total number of connector tasks.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_total_task_count{job=\"$job\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Running tasks",
   "type": "stat",
   "description": "The total number of running connector tasks.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_running_task_count{job=\"$job\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Failed tasks",
   "type": "stat",
   "description": "The total number of failed connector tasks.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_failed_task_count{job=\"$job\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Paused tasks",
   "type": "stat",
   "description": "The total number of paused connector tasks.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_paused_task_count{job=\"$job\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Unassigned tasks",
   "type": "stat",
   "description": "The total number of unassigned connector tasks.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_unassigned_task_count{job=\"$job\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Destroyed tasks",
   "type": "stat",
   "description": "The total number of destroyed connector tasks.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_destroyed_task_count{job=\"$job\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Connector and task status",
   "type": "table",
   "description": "The current status of connectors and their tasks.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "min(kafka_connect_connector_status{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector, status)"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_total_task_count{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector)"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_running_task_count{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector) "
    },
    {
     "expr": "sum(kafka_connect_worker_connector_failed_task_count{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector)"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_paused_task_count{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector)"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_unassigned_task_count{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector)"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_destroyed_task_count{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector)"
    }
   ]
  },
  {
   "title": "Connector status over time",
   "type": "timeseries",
   "description": "The status of connectors over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(kafka_connect_connector_status{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\", status=\"running\"}) by (status)",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kafka_connect_connector_status{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\", status=\"failed\"}) by (status)",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(kafka_connect_connector_status{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\", status=\"paused\"}) by (status)",
     "legendFormat": "Paused"
    },
    {
     "expr": "sum(kafka_connect_connector_status{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\", status=\"unassigned\"}) by (status)",
     "legendFormat": "Unassigned"
    },
    {
     "expr": "sum(kafka_connect_connector_status{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\", status=\"destroyed\"}) by (status)",
     "legendFormat": "Destroyed"
    }
   ]
  },
  {
   "title": "Connector task status over time",
   "type": "timeseries",
   "description": "The status of connector tasks over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_running_task_count{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) > 0",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_failed_task_count{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) > 0",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_paused_task_count{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) > 0",
     "legendFormat": "Paused"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_unassigned_task_count{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) > 0",
     "legendFormat": "Unassigned"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_destroyed_task_count{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) > 0",
     "legendFormat": "Destroyed"
    }
   ]
  },
  {
   "title": "Time since last rebalance [$worker]",
   "type": "stat",
   "description": "The time since last rebalance of Kafka Mirror Maker worker.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 21 },
   "repeat": "worker",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_worker_rebalance_time_since_last_rebalance_ms{job=\"$job\", instance=~\".*$worker.*\"} >= 0"
    }
   ]
  },
  {
   "title": "Mirror Maker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replicated topics",
     "type": "table",
     "description": "Replication statistics for topics.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "min(label_join(kafka_connect_mirror_source_connector_record_count{job=\"$job\", instance=~\".*$worker.*\", topic=~\".+\", partition=~\".+\", source=~\".+\", target=~\".+\"}, \"topicAndPartitionAndSourceAndTarget\", \"-\", \"topic\", \"partition\", \"source\", \"target\")) by (topicAndPartitionAndSourceAndTarget, topic, partition, source, target)"
      },
      {
       "expr": "min(label_join(kafka_connect_mirror_source_connector_byte_count{job=\"$job\", instance=~\".*$worker.*\", topic=~\".+\", partition=~\".+\", source=~\".+\", target=~\".+\"}, \"topicAndPartitionAndSourceAndTarget\", \"-\", \"topic\", \"partition\", \"source\", \"target\")) by (topicAndPartitionAndSourceAndTarget, topic, partition, source, target)"
      }
     ]
    },
    {
     "title": "Records replicated per second",
     "type": "timeseries",
     "description": "The number of records replicated per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(kafka_connect_mirror_source_connector_record_count{job=\"$job\", instance=~\".*$worker.*\", topic=~\".+\", partition=~\".+\", source=~\".+\", target=~\".+\"}[5m])",
       "legendFormat": "{{topic}}-{{partition}} [direction=\"{{source}}->{{target}}\"]"
      }
     ]
    },
    {
     "title": "Records in bytes replicated per second",
     "type": "timeseries",
     "description": "The number of records in bytes replicated per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(kafka_connect_mirror_source_connector_byte_count{job=\"$job\", instance=~\".*$worker.*\", topic=~\".+\", partition=~\".+\", source=~\".+\", target=~\".+\"}[5m])",
       "legendFormat": "{{topic}}-{{partition}} [direction=\"{{source}}->{{target}}\"]"
      }
     ]
    },
    {
     "title": "Replication latency",
     "type": "timeseries",
     "description": "The average time in milliseconds taken to replicate records from source to target cluster.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(kafka_connect_mirror_source_connector_replication_latency_ms_avg{job=\"$job\", instance=~\".*$worker.*\", topic=~\".+\", partition=~\".+\", source=~\".+\", target=~\".+\"}) by (topic, partition, source, target)",
       "legendFormat": "{{topic}}-{{partition}} [direction=\"{{source}}->{{target}}\"]"
      }
     ]
    },
    {
     "title": "Checkpoint latency",
     "type": "timeseries",
     "description": "The average time in milliseconds taken to replicate consumer offsets.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(kafka_connect_mirror_checkpoint_connector_checkpoint_latency_ms_avg{job=\"$job\", instance=~\".*$worker.*\", topic=~\".+\", partition=~\".+\", group=~\".+\", source=~\".+\", target=~\".+\"}) by (topic, partition, group, source, target)",
       "legendFormat": "{{topic}}-{{partition}} [group={{group}}, direction=\"{{source}}->{{target}}\"]"
      }
     ]
    },
    {
     "title": "Record age",
     "type": "timeseries",
     "description": "The average age of records in milliseconds when they are replicated.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(kafka_connect_mirror_source_connector_record_age_ms_avg{job=\"$job\", instance=~\".*$worker.*\", topic=~\".+\", partition=~\".+\", source=~\".+\", target=~\".+\"}) by (topic, partition, source, target)",
       "legendFormat": "{{topic}}-{{partition}} [direction=\"{{source}}->{{target}}\"]"
      }
     ]
    }
   ]
  },
  {
   "title": "Connector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Source records polled per second (before transformation)",
     "type": "timeseries",
     "description": "The per-second number of source records produced/polled (before transformation) by connector task.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(kafka_connect_source_task_source_record_poll_total{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}[5m])",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Source records written per second (after transformation)",
     "type": "timeseries",
     "description": "The per-second number of source records output from the transformations and written to Kafka for connector task. This is after transformations are applied and excludes any records filtered out by the transformations.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(kafka_connect_source_task_source_record_write_total{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}[5m])",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Source record poll time",
     "type": "timeseries",
     "description": "The average time in milliseconds taken by connector task to poll for a batch of source records.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(kafka_connect_source_task_poll_batch_avg_time_ms{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}) by (connector, task)",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Task batch size",
     "type": "timeseries",
     "description": "The average size of the batches processed by the connector task.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "kafka_connect_connector_task_batch_size_avg{job=\"$job\", instance=~\".*$worker.*\", connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Producer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Producers",
     "type": "table",
     "description": "Statistics of connector producers for topics.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "min(label_join(kafka_producer_topic_record_send_total{job=\"$job\", instance=~\".*$worker.*\", clientId=~\"connector-producer-$connector.*\", topic=~\".+\"}, \"clientIdAndTopic\", \"-\", \"clientId\", \"topic\")) by (clientIdAndTopic, clientId, topic)"
      },
      {
       "expr": "min(label_join(kafka_producer_topic_byte_total{job=\"$job\", instance=~\".*$worker.*\", clientId=~\"connector-producer-$connector.*\", topic=~\".+\"}, \"clientIdAndTopic\", \"-\", \"clientId\", \"topic\")) by (clientIdAndTopic, clientId, topic)"
      }
     ]
    },
    {
     "title": "Records sent per second",
     "type": "timeseries",
     "description": "The number of records sent per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(kafka_producer_topic_record_send_total{job=\"$job\", instance=~\".*$worker.*\", clientId=~\"connector-producer-$connector.*\", topic=~\".+\"}[5m])",
       "legendFormat": "{{clientId}} [topic={{topic}}]"
      }
     ]
    },
    {
     "title": "Records in bytes sent per second",
     "type": "timeseries",
     "description": "The number of records in bytes sent per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(kafka_producer_topic_byte_total{job=\"$job\", instance=~\".*$worker.*\", clientId=~\"connector-producer-$connector.*\"}[5m])",
       "legendFormat": "{{clientId}} [topic={{topic}}]"
      }
     ]
    },
    {
     "title": "Producer record queue time",
     "type": "timeseries",
     "description": "The average time in milliseconds record batches spent in the send buffer.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(kafka_producer_record_queue_time_avg{job=\"$job\", instance=~\".*$worker.*\", clientId=~\"connector-producer-$connector.*\"}) by (clientId)",
       "legendFormat": "{{clientId}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consumers",
     "type": "table",
     "description": "Statistics of connector consumers for topics.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "min(label_join(kafka_consumer_fetch_manager_records_consumed_total{job=\"$job\", instance=~\".*$worker.*\", clientId=~\".*replication-consumer.*\", topic=~\".+\"}, \"clientIdAndTopic\", \"-\", \"clientId\", \"topic\")) by (clientIdAndTopic, clientId, topic)"
      },
      {
       "expr": "min(label_join(kafka_consumer_fetch_manager_bytes_consumed_total{job=\"$job\", instance=~\".*$worker.*\", clientId=~\".*replication-consumer.*\", topic=~\".+\"}, \"clientIdAndTopic\", \"-\", \"clientId\", \"topic\")) by (clientIdAndTopic, clientId, topic)"
      }
     ]
    },
    {
     "title": "Records consumed per second",
     "type": "timeseries",
     "description": "The number of records consumed per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(kafka_consumer_fetch_manager_records_consumed_total{job=\"$job\", instance=~\".*$worker.*\", clientId=~\".*replication-consumer.*\", topic=~\".+\"}[5m])",
       "legendFormat": "{{clientId}} [topic={{topic}}]"
      }
     ]
    },
    {
     "title": "Records in bytes consumed per second",
     "type": "timeseries",
     "description": "The number of records in bytes consumed per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(kafka_consumer_fetch_manager_bytes_consumed_total{job=\"$job\", instance=~\".*$worker.*\", clientId=~\".*replication-consumer.*\", topic=~\".+\"}[5m])",
       "legendFormat": "{{clientId}} [topic={{topic}}]"
      }
     ]
    },
    {
     "title": "Consumer lag",
     "type": "timeseries",
     "description": "The lag in terms of number of records by clients. An increasing value over time is your best indication that the consumer group is not keeping up with the producers.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "sum(kafka_consumer_fetch_manager_records_lag{job=\"$job\", instance=~\".*$worker.*\", clientId=~\".*replication-consumer.*\", topic=~\".+\"}) by (clientId, topic)",
       "legendFormat": "{{clientId}} [topic={{topic}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Worker: $worker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "repeat": "worker",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage [$worker]",
     "type": "timeseries",
     "description": "The information about CPU usage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"$job\", instance=~\".*$worker.*\"}[5m])",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Threads [$worker]",
     "type": "timeseries",
     "description": "The information about JVM threads.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "jvm_threads_current{job=\"$job\", instance=~\".*$worker.*\"}",
       "legendFormat": "Total threads"
      },
      {
       "expr": "jvm_threads_daemon{job=\"$job\", instance=~\".*$worker.*\"}",
       "legendFormat": "Daemon threads"
      },
      {
       "expr": "jvm_threads_deadlocked{job=\"$job\", instance=~\".*$worker.*\"}",
       "legendFormat": "Deadlocked threads"
      }
     ]
    },
    {
     "title": "Heap memory usage [$worker]",
     "type": "timeseries",
     "description": "The information about JVM heap memory usage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{area=\"heap\", job=\"$job\", instance=~\".*$worker.*\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_bytes_max{area=\"heap\", job=\"$job\", instance=~\".*$worker.*\"}",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Garbage collections triggered per second [$worker]",
     "type": "timeseries",
     "description": "The number of garbage collections triggered per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_count{job=\"$job\", instance=~\".*$worker.*\"}[5m])",
       "legendFormat": "{{gc}}"
      }
     ]
    },
    {
     "title": "Heap memory usage in percent [$worker]",
     "type": "timeseries",
     "description": "The information about JVM heap memory usage in percent (%).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * jvm_memory_bytes_used{area=\"heap\", job=\"$job\", instance=~\".*$worker.*\"} / jvm_memory_bytes_max{area=\"heap\", job=\"$job\", instance=~\".*$worker.*\"}",
       "legendFormat": "Used"
      },
      { "expr": "100", "legendFormat": "Limit" }
     ]
    },
    {
     "title": "Time spent in garbage collection [$worker]",
     "type": "timeseries",
     "description": "The time in seconds spent in garbage collection.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{job=\"$job\", instance=~\".*$worker.*\"}[5m])",
       "legendFormat": "{{gc}}"
      }
     ]
    }
   ]
  }
 ]
}