lowercaseOutputName: true
rules:
  #kafka.streams:type=stream-thread-metrics,thread-id="{threadid}"
  - pattern: kafka.streams<type=stream-thread-metrics, thread-id=(.+)><>(.+-avg|.+-rate|.+-total|.+-ratio)
    name: kafka_streams_thread_$2
    labels:
      threadId: "$1"
    help: "JMX metric of a Kafka stream thread"
    type: GAUGE

  #kafka.streams:type=stream-state-metrics,thread-id="{threadid}",task-id="{taskid}",[store-type]-state-id="{storeid}"
  - pattern: kafka.streams<type=stream-state-metrics, thread-id=(.+), task-id=(.+), (.+)-state-id=(.+)><>(.+-avg|.+-rate|.+-total|size-all-mem-tables|block-cache-usage|estimate-table-readers-mem|total-sst-files-size)
    name: kafka_streams_state_$5
    labels:
      threadId: "$1"
      taskId: "$2"
      storeType: "$3"
      storeId: "$4"
    help: "JMX metric of a Kafka stream state store"
    type: GAUGE

  #kafka.streams:type=stream-metrics,client-id="{clientid}"
  - pattern: kafka.streams<type=stream-metrics, client-id=(.+)>alive-stream-threads
    name: kafka_streams_alive_stream_threads
    labels:
      clientId: "$1"
    help: "Number of alive stream threads in a Kafka stream"
    type: GAUGE
  - pattern: kafka.streams<type=stream-metrics, client-id=(.+)>failed-stream-threads
    name: kafka_streams_failed_stream_threads
    labels:
      clientId: "$1"
    help: "Number of failed stream threads in a Kafka stream"
    type: GAUGE

  #kafka.streams:type=stream-metrics,client-id="{clientid}"<>state
  - pattern: 'kafka.streams<type=stream-metrics, client-id=(.+)><>state: (CREATED|RUNNING|REBALANCING|ERROR|PENDING SHUTDOWN|NOT RUNNING)'
    name: kafka_streams_state
    value: 1
    labels:
      clientId: "$1"
      state: "$2"
    help: "Kafka stream client state"
    type: GAUGE

  #kafka.streams:type=stream-metrics,client-id="{clientid}"
  - pattern: 'kafka.streams<type=stream-metrics, client-id=(.+)><>(application-id|commit-id|version): (.+)'
    name: kafka_streams_$2_info
    value: 1
    labels:
      clientId: "$1"
      $2: "$3"
    help: "Kafka stream JMX metric info version, commit-id and application-id"
    type: GAUGE

  #kafka.consumer:type=app-info,client-id="{clientid}"
  #kafka.producer:type=app-info,client-id="{clientid}"
  - pattern: kafka.(.+)<type=app-info, client-id=(.+)><>start-time-ms
    name: kafka_$1_start_time_seconds
    labels:
      clientId: "$2"
    help: "Kafka $1 JMX metric start time seconds"
    type: GAUGE
    valueFactor: 0.001
  - pattern: 'kafka.(.+)<type=app-info, client-id=(.+)><>(commit-id|version): (.+)'
    name: kafka_$1_$3_info
    value: 1
    labels:
      clientId: "$2"
      $3: "$4"
    help: "Kafka $1 JMX metric info version and commit-id"
    type: GAUGE

  #kafka.producer:type=producer-topic-metrics,client-id="{clientid}",topic="{topic}",partition="{partition}"
  #kafka.consumer:type=consumer-fetch-manager-metrics,client-id="{clientid}",topic="{topic}",partition="{partition}"
  - pattern: kafka.(.+)<type=(.+)-metrics, client-id=(.+), topic=(.+), partition=(.+)><>(.+-total|compression-rate|.+-avg|.+-replica|.+-lag|.+-lead)
    name: kafka_$2_$6
    labels:
      clientId: "$3"
      topic: "$4"
      partition: "$5"
    help: "Kafka $1 JMX metric type $2"
    type: GAUGE

  #kafka.producer:type=producer-topic-metrics,client-id="{clientid}",topic="{topic}"
  #kafka.consumer:type=consumer-fetch-manager-metrics,client-id="{clientid}",topic="{topic}",partition="{partition}"
  - pattern: kafka.(.+)<type=(.+)-metrics, client-id=(.+), topic=(.+)><>(.+-total|compression-rate|.+-avg)
    name: kafka_$2_$5
    labels:
      clientId: "$3"
      topic: "$4"
    help: "Kafka $1 JMX metric type $2"
    type: GAUGE

  #kafka.consumer:type=consumer-node-metrics,client-id=consumer-1,node-id="{nodeid}"
  - pattern: kafka.(.+)<type=(.+)-metrics, client-id=(.+), node-id=(.+)><>(.+-total|.+-avg)
    name: kafka_$2_$5
    labels:
      clientId: "$3"
      nodeId: "$4"
    help: "Kafka $1 JMX metric type $2"
    type: UNTYPED

  #kafka.consumer:type=consumer-fetch-manager-metrics,client-id="{clientid}"
  #kafka.consumer:type=consumer-coordinator-metrics,client-id="{clientid}"
  #kafka.consumer:type=consumer-metrics,client-id="{clientid}"
  - pattern: kafka.(.+)<type=(.+)-metrics, client-id=(.*)><>(.+-total|.+-avg|.+-bytes|.+-count|.+-ratio|.+-age|.+-flight|.+-threads|.+-ago)
    name: kafka_$2_$4
    labels:
      clientId: "$3"
    help: "Kafka $1 JMX metric type $2"
    type: GAUGE
